version: '3.8'

## DEFINE SERVICES
services:
  ## CRYPTO API
  crypto-tools-api:
    container_name: CRYPTO-TOOLS-API
    image: crypto-tools-api:dev
    build: ./
    command: uvicorn src.app:app --host 0.0.0.0 --port 4130
    volumes:
      - .:/api
    ports:
      - 4130:4130